runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static
  application_readable: true
- url: /drafts
  static_dir: drafts
- url: .*
  script : start.application

env_variables:
  SELENIUM_ENABLED: false
  USE_MEM_DB: true
