config = {
    "name_differences": {
        "A.J. Green": "AJ Green",
        "Odell Beckham Jr.": "Odell Beckham",
        "T.Y. Hilton": "TY Hilton",
        "C.J. Anderson": "CJ Anderson",
        "C.J. Prosise": "CJ Prosise",
        "O.J. Howard": "OJ Howard",
        "Robert Kelley": "Rob Kelley",
        "Devante Parker": "DeVante Parker",
        "C.J. Fiedorowicz": "CJ Fiedorowicz",
        "J.J. Nelson": "JJ Nelson",
        "T.J. Yeldon": "TJ Yeldon",
        "A.J. Derby": "AJ Derby",
        "T.J. Logan": "TJ Logan",
        "Benjamin Watson": "Ben Watson",
        "Desean Jackson": "DeSean Jackson",
        "Quincy Enuwa": "Quincy Enunwa",
        "Deandre Washington": "DeAndre Washington",
        "Le'veon Bell": "Le'Veon Bell",
        "Christian McCaffery": "Christian McCaffrey",
        "Donnell Pumphrey": "Donnel Pumphrey",
        "Juju Smith-Schuster": "JuJu Smith-Schuster",
    }
}
