config = {
    "name_differences": {
        "A.J. Green": "AJ Green",
        "Odell Beckham Jr.": "Odell Beckham",
        "T.Y. Hilton": "TY Hilton",
        "C.J. Anderson": "CJ Anderson",
        "C.J. Prosise": "CJ Prosise",
        "O.J. Howard": "OJ Howard",
        "Robert Kelley": "Rob Kelley",
        "Devante Parker": "DeVante Parker",
        "C.J. Fiedorowicz": "CJ Fiedorowicz",
        "J.J. Nelson": "JJ Nelson",
        "T.J. Yeldon": "TJ Yeldon",
        "A.J. Derby": "AJ Derby",
        "T.J. Logan": "TJ Logan",
        "Benjamin Watson": "Ben Watson",
        "Desean Jackson": "DeSean Jackson",
        "Quincy Enuwa": "Quincy Enunwa",
        "Deandre Washington": "DeAndre Washington",
        "Le'veon Bell": "Le'Veon Bell",
        "Christian McCaffery": "Christian McCaffrey",
        "Donnell Pumphrey": "Donnel Pumphrey",
        "Juju Smith-Schuster": "JuJu Smith-Schuster",
        "Deangelo Williams": "DeAngelo Williams",
	    "Ardarius Stewart": "ArDarius Stewart",
        "J.D. McKissic": "JD McKissic",
        "RIcky Seals-Jones": "Ricky Seals-Jones",
        "Lesean McCoy": "LeSean McCoy",
        "Mike GIllislee": "Mike Gillislee",
        "C.J. Beathard": "CJ Beathard",
        "Demarco Murray": "DeMarco Murray",
        "Le'Veon Bell": "LeVeon Bell",
        "Ronald Jones II": "Ronald Jones",
        "D.J. Moore": "DJ Moore",
        "Mitch Trubisky": "Mitchell Trubisky",
        "D'Onta Foreman": "DOnta Foreman",
        "D.J. Chark": "DJ Chark",
        "De'Angelo Henderson": "DeAngelo Henderson",
        "J'Mon Moore": "JMon Moore",
        "Tre'Quan Smith": "TreQuan Smith",
        "Equanimeous St. Brown": "Equanimeous St Brown",
        "Nick O'Leary": "Nick OLeary",
        "Chris Herndon IV": "Chris Herndon",
        "D.J. Foster": "DJ Foster",
        "Chris Warren": "Chris Warren III",
        "Daesean Hamilton": "DaeSean Hamilton",
        "N'Keal Harry": "NKeal Harry",
        "D.K. Metcalf": "DK Metcalf",
        "A.J. Brown": "AJ Brown",
        "T.J. Hockenson": "TJ Hockenson",
        "J.J. Arcega-Whiteside": "JJ Arcega-Whiteside",
        "C.J. Uzomah": "CJ Uzomah",
        "Benny Snell Jr.": "Benny Snell",
        "Irv Smith Jr.": "Irv Smith",
        "Jeff Wilson": "Jeffery Wilson",
        "James O'Shaughnessy": "James OShaughnessy",
        "Gregory Howell": "Buddy Howell",
        "Alex Armah": "Alexander Armah",
        "Mark Ingram II": "Mark Ingram",
        "Gardner Minshew II": "Gardner Minshew",
        "Laviska Shenault": "Laviska Shenault Jr.",
        "K.J. Hamler": "KJ Hamler",
        "Le'veon Bell": "LeVeon Bell",
        "La'Mical Perine": "Lamical Perine",
    }
}
