""" Redraft Rank, Tier and Bye week

Revision ID: 37e881b48d69
Revises: 9018e062992b
Create Date: 2017-06-16 14:56:35.438978

"""

# revision identifiers, used by Alembic.
revision = '37e881b48d69'
down_revision = '9018e062992b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('bye', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('redraft_rank', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('redraft_tier', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'redraft_tier')
    op.drop_column('players', 'redraft_rank')
    op.drop_column('players', 'bye')
    ### end Alembic commands ###
