"""Add redraft value (should be temporary)

Revision ID: e001c4dfa0ee
Revises: 37e881b48d69
Create Date: 2017-07-04 08:35:24.586919

"""

# revision identifiers, used by Alembic.
revision = 'e001c4dfa0ee'
down_revision = '37e881b48d69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('redraft_value', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'redraft_value')
    ### end Alembic commands ###
